--SELECT * FROM cleaned_data;

--Q1. What is the total revenue generated by male vs. female customers?
--select c3, SUM(c6) as revenue
--from cleaned_data
--group by c3;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
--select c1, c6 
--from cleaned_data
--where c14 = 'Yes' and c6 >= (select AVG(c6) from cleaned_data);

-- Q3. Which are the top 5 products with the highest average review rating?
--select c4, round(avg(c11),2) as "Average Product Rating"
--from cleaned_data
--group by c4
--order by avg(c11) desc
--limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
--select c13, 
--ROUND(AVG(c6),2)
--from cleaned_data
--where c13 in ('Standard','Express')
--group by c13;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
--SELECT c12,
--       COUNT(c1) AS total_customers,
--       ROUND(AVG(c6),2) AS avg_spend,
--       ROUND(SUM(c6),2) AS total_revenue
--FROM cleaned_data
--GROUP BY c12
--ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
--SELECT c4,
--       ROUND(100.0 * SUM(CASE WHEN c14 = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
--FROM cleaned_data
--GROUP BY c4
--ORDER BY c14 DESC
--LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
--with customer_type as (
--SELECT c1, c15,
--CASE 
--    WHEN c15 = 1 THEN 'New'
--    WHEN c15 BETWEEN 2 AND 10 THEN 'Returning'
--    ELSE 'Loyal'
--    END AS customer_segment
--FROM cleaned_data)

--select customer_segment,count(*) AS "Number of Customers" 
--from customer_type
--group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
--WITH item_counts AS (
--    SELECT c5,
--           c4,
--           COUNT(c1) AS total_orders,
--           ROW_NUMBER() OVER (PARTITION BY c5 ORDER BY COUNT(c1) DESC) AS item_rank
--    FROM cleaned_data
--    GROUP BY c5, c4
--)
--SELECT item_rank,c5, c4, total_orders
--FROM item_counts
--WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
--SELECT c12,
--       COUNT(c1) AS repeat_buyers
--FROM cleaned_data
--WHERE c15 > 5
--GROUP BY c12;

--Q10. What is the revenue contribution of each age group? 
--SELECT 
--    c18,
--    SUM(c6) AS total_revenue
--FROM cleaned_data
--GROUP BY c18
--ORDER BY total_revenue desc;